language: php

dist: trusty
sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files
        - .phpunit

matrix:
    include:
        - php: 7.1
        - php: nightly
          env: composer_extra="--prefer-lowest"
    fast_finish: true

install:
    - composer $composer_extra update

script:
    - ./vendor/bin/simple-phpunit
